### ISSUE TITLE
Consider using Markdown over MS Word

### ISSUE THREAD

**Issue by kuc2477** [theverytak/readingHBR#1]
I think it will give you some flexibility and better structure to your notes, which are good things for your possible future static blog or wiki website. 

But most of all, I want to subscribe your notes and read them on Github directly. Github doesn't provide preview for .docx format.

**Comment by theverytak** [comment]
Dear Jun,
It was a really delightful moment to get your unexepected e-mail. This
morning I woke up to feel very cold, but not it isn't.
That was a really good point to use a md file. Later it will be added.
By the way, it feels a little bit crippy because it hasn't passed even a
day since I made that new repository. So glad that you keep watching my
repo, but someone may feel just as, if not more, embarassed. Anyway thank
you.
It will be good if we read HBR together.

Stop peeping into my repository. You are like a 쥐새끼.

V/R
Ji

2016-10-14 9:21 GMT+09:00 Ha Junsoo notifications@github.com:

**Comment by kuc2477** [comment]
I don't peep into your repo. It's just my daily routine to pick up interesting feeds from my Github dashboard and take a look at them to see if there's any attractive project. I've looked around because your project showed up in my dashboard and that's all.

**Comment by kuc2477** [comment]
BTW, my passport english name is June, not Jun.

**Comment by theverytak** [comment]
kkkkkkk for me, "Tag" is my legal name.
So sweet that you think of my repo as an attractive one, but remove mine out at your game list.
Thank you, Jun.

**Comment by theverytak** [comment]
And I think your country won't allow you to choose looking around github as your daily routine, will it?
Maybe the word "country" can be replaced to "company"
