### ISSUE TITLE
There's some problems with parsing.

### ISSUE THREAD

**Issue by theverytak** [theverytak/readingHBR#8]
Appreciating your interest and commit, @kuc2477.
While enjoying the quiz, there's some problem with reading the words.
If you take the 10.31 quiz, you will get the picture. I think  " ' "is miss-used when the word is parsed into English and Hangul.
Also, recently I try to add some notes about how I feel or short summary about the article at the end of the file, and I don't want it to show up on the slides. Later I will place a word such as 느낀점 before that paragraph, though 느낀점 doesn't sound cool enough.

**Comment by kuc2477** [comment]
Thanks for reporting issues for my humble toy parser.

I fixed the parsing issue with  " ' " in PR #9. It's been tested in my environment and merging it should fix the problem.

I'm aware of the issues that adding summary brings up to us. The very root of the problem is that current parser can't differentiate your vocabulary notes from summary without any proper markup protocol. 

I believe placing some bold markup title like **느낀점** before your summaries will just work right away since our quiz generator is explicitly targeting at only **단어** and **문장** markup titles in `takequiz.py`

**Comment by theverytak** [comment]
I will add **요약** before my summary. Thank you!
I wish your quiz being "immaculate" - look up 10.22.md if you aren't familiar with this one :)
